### ISSUE TITLE
Windows ARM64 version of GUI?

### ISSUE THREAD

**Issue by tommyvct** [chiragsakhuja/lc3tools#19]
I tried to compile my own version of GUI, but there are way too many linker arch mismatch errors. 

I followed [this cross build guide](https://www.electronjs.org/docs/tutorial/windows-arm), but it's not enough. Parts of it are also out of date.

**Comment by chiragsakhuja** [comment]
Are you cross-compiling from x86 Windows, or are you compiling directly on ARM64 Windows?  I haven't tried either case, but in theory they should both work.

First, you'll need to build the LC3Tools static library, which is located at `build/Release/lib/lc3core.lib`, for ARM64.  I assume most of the linker errors you're getting are because the library is built for x86 by default.  In Visual Studio 2019, you can open up the CMakeSettings.json file and then change the Toolset from msvc_x64_x64 to either msvc_arm64_x64 (if you're cross-compiling) or msvc_arm64 (if you're running on ARM64 Windows).  If you're cross-compiling, it might be helpful create a new Release configuration in CMakeSettings.json for ARM64 *.

Once you've built the ARM64 library, you should be able to follow the cross build guide.  Unfortunately I don't have the time to test out any of this right now, but feel free to follow up here if these steps still don't work.

* If you change the configuration name, you may need to update the library path on line 30 of `src/gui/local_modules/lc3interface/binding.gyp` file.

**Comment by chiragsakhuja** [comment]
I just looked a little more carefully at the cross build guide and noticed that it requires at least Electron 6.0.8, whereas the project currently uses Electron 3.1.13.  I changed the `src/gui/package.json` to use a more recent version of Electron, and I'm getting some errors when I launch the `yarn run dev`.

I do plan on upgrading the packages at some point, but as I mentioned before I don't have the bandwidth right now.  Unless you want to try to dig deeper yourself to resolve the issues, my suggestion is to try using an x86 Linux virtual machine for the time being.  Sorry I can't be of more help.

**Comment by tommyvct** [comment]
Thanks!
The C/C++ binaries compiled just fine. 

The problem is the GUI part.
I'm new to JavaScript, I'll try to learn and fix it. Not a pleasant journey so far.

**Comment by chiragsakhuja** [comment]
I'm not sure if this issue is still relevant, but Windows 11 running on ARM systems can now do binary translation from x86, so the x86 version in the Releases tab should work on ARM systems. Since there hasn't been an activity here in a year, I'm going to close this issue.
