### ISSUE TITLE
Feature request: disallow  use of constants as operands in PC+displacement context 

### ISSUE THREAD

**Issue by owenkaser** [chiragsakhuja/lc3tools#25]
Last two years, I have had a group of students who have internalized-machine language programming so well that they want to write assembly loops like
       .orig x3000
    MyLoop  add r0, r0, r0
                   BRp  -2

I would like this to be illegal (at least by default).  Anyway, if expression  "MyLoop" were viewed as evaluating to x3000, then I guess   BRp x3000 might be logically defensible as an alternative to BRp MyLoop, but  -2?  Maybe the person is hoping to branch to address FFFE, not backwards by 2....

**Comment by chiragsakhuja** [comment]
Dr. Yale Patt (one of the authors of the textbook) has specifically requested for this behavior since it follows directly from the ISA description, so I'll unfortunately have to defer to his discretion.  If you'd like to change this behavior for your class, I'm happy to guide you through the necessary modifications.  I don't envision future merge conflicts with the files, but you would have to have to manage your custom releases yourself.

**Comment by owenkaser** [comment]
I don't feel strongly enough about this to maintain a custom release.
Thanks for the offer, though.

**Comment by chiragsakhuja** [comment]
Closing, since this behavior won't change.
